// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADXg4BBDqg1DRUZudk0_mXgCArSBosAKQ',
    appId: '1:169373647693:web:1697b42b705f4f0c072d04',
    messagingSenderId: '169373647693',
    projectId: 'desbrava-app-7c347',
    authDomain: 'desbrava-app-7c347.firebaseapp.com',
    storageBucket: 'desbrava-app-7c347.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fJeMSIIdjSOm0zCe_sghKrFsfYKL19g',
    appId: '1:169373647693:android:36880c922c6d6fa1072d04',
    messagingSenderId: '169373647693',
    projectId: 'desbrava-app-7c347',
    storageBucket: 'desbrava-app-7c347.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJMJf_jgx3QJQ7FIjvc1Ib5F6kN1suUg',
    appId: '1:169373647693:ios:49a306a252411220072d04',
    messagingSenderId: '169373647693',
    projectId: 'desbrava-app-7c347',
    storageBucket: 'desbrava-app-7c347.firebasestorage.app',
    iosBundleId: 'com.example.myDesbrava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpJMJf_jgx3QJQ7FIjvc1Ib5F6kN1suUg',
    appId: '1:169373647693:ios:49a306a252411220072d04',
    messagingSenderId: '169373647693',
    projectId: 'desbrava-app-7c347',
    storageBucket: 'desbrava-app-7c347.firebasestorage.app',
    iosBundleId: 'com.example.myDesbrava',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADXg4BBDqg1DRUZudk0_mXgCArSBosAKQ',
    appId: '1:169373647693:web:1999f7d7451090a9072d04',
    messagingSenderId: '169373647693',
    projectId: 'desbrava-app-7c347',
    authDomain: 'desbrava-app-7c347.firebaseapp.com',
    storageBucket: 'desbrava-app-7c347.firebasestorage.app',
  );
}
